custom:
  client:
    bucketName: serverless-s3-sample
    distributionFolder: build
    indexDocument: index.html
    errorDocument: index.html
    bucketPolicyFile: config/bucket-policy.json

service: serverless-s3
fromworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x

plugins:
  - serverless-finch
